### ISSUE TITLE
New user sign up

### ISSUE THREAD

**Issue by UG-Asger** [Moc/events2bots#4]
Hi

It seems the new user sign up exports the users email to Discord. According to GDPR this is bad ;( 
Would it be possible to remove that? Should only be user or display name or both?

**Comment by Moc** [comment]
Done. You can update with the latest files from Github or wait for the official release.

**Comment by UG-Asger** [comment]
Hi. 
![image](https://user-images.githubusercontent.com/68121399/110210372-a5af0300-7e91-11eb-9f01-8ba4a0d59183.png)
 User name/display name is not exported ;) But the email is removed :)
